### test sign-up
POST https://localhost:3000/users/signup
content-type: application/json

{
    "name":"liam3",
    "email":"liam334@rd.com",
    "password":"111111111111",
    "roles":["admin"]
}


### test sign-up
POST http://localhost:80/users/signup
content-type: application/json

{
    "name":"jack",
    "email":"jack@rd.com",
    "password":"22222222222222222222",
    "roles":["admin"]
}

### test sign-in
POST https://localhost:3000/users/signin
content-type: application/json

{
    "email":"liam3@rd.com",
    "password":"111111111111"
}

### test sign-out
POST https://localhost:3000/users/signout

### test get flights
GET  https://localhost:3000/flights/

### test get flights
GET  http://localhost:80/flights/

### test get flights
GET  http://localhost:3000/flights/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODNmNGE5MDQ2NTMxYmE0ZmY5Y2VjMTkiLCJyb2xlcyI6WyJzdGFmZl9sMSIsImRlbGV0ZV9mbGlnaHQiXSwiaWF0IjoxNzQ4OTgwMzAyfQ.stnC4IwSRvRZSfPVCFSUWvknSlxf8dUqCRDT1DiAB_g