### test sign-up
POST http://localhost:5000/users/signup
content-type: application/json

{
    "name":"reza",
    "email":"rich@rd22.com",
    "password":"4444455555",
    "roles":["staff_l1", "delete_flight"]
}

### test sign-in
POST http://localhost:5000/users/signin
content-type: application/json

{
    "email":"rich@rd22.com",
    "password":"4444455555"
}

### test get flights
GET  http://localhost:5000/flights/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODNmNGE5MDQ2NTMxYmE0ZmY5Y2VjMTkiLCJyb2xlcyI6WyJzdGFmZl9sMSIsImRlbGV0ZV9mbGlnaHQiXSwiaWF0IjoxNzQ4OTgwMzAyfQ.stnC4IwSRvRZSfPVCFSUWvknSlxf8dUqCRDT1DiAB_g